<script lang="ts">
import type { PageTree } from "@docvia/source";
import { page } from "$app/state";
import { cn } from "$lib/utils";
import { ChevronRight } from "@lucide/svelte";

// The navigation tree is generated by docvia from the compiled `docs`
// collection — see `+layout.server.ts`. The docs site dogfoods the compiler.
let { tree, mobile = false }: { tree: PageTree.Root; mobile?: boolean } =
	$props();

type Group = {
	name: string;
	overview?: PageTree.Item;
	pages: PageTree.Item[];
	prefix: string;
};

// Eighteen siblings all beginning "@docvia/" cost a scan on every row. Show the
// prefix once on the group and strip it from the labels.
function sharedPrefix(names: string[]): string {
	if (names.length < 3) return "";
	const cut = names[0].indexOf("/");
	if (cut < 0) return "";
	const candidate = names[0].slice(0, cut + 1);
	return names.every((n) => n.startsWith(candidate)) ? candidate : "";
}

const activeUrl = $derived(page.url.pathname);
const rootPages = $derived(tree.children.filter((n) => n.type === "page"));

const groups = $derived<Group[]>(
	tree.children
		.filter((n) => n.type === "folder")
		.map((folder) => {
			const pages = folder.children.flatMap((child) =>
				child.type === "page"
					? [child]
					: child.type === "folder" && child.index
						? [child.index]
						: [],
			);
			return {
				name: folder.name,
				overview: folder.index,
				pages,
				prefix: sharedPrefix(pages.map((p) => p.name)),
			};
		}),
);

let toggled = $state<Record<string, boolean>>({});

function holdsActive(group: Group): boolean {
	return (
		group.overview?.url === activeUrl ||
		group.pages.some((p) => p.url === activeUrl)
	);
}

// Default open state follows the URL so the server and client agree and no
// group flashes shut on hydration. An explicit toggle outranks it.
function isOpen(group: Group): boolean {
	return toggled[group.name] ?? holdsActive(group);
}

let scrollEl = $state<HTMLElement | null>(null);

// Landing deep in a long group otherwise renders the rail scrolled to the top
// with the current page below the fold.
$effect(() => {
	activeUrl;
	const box = scrollEl;
	const el = box?.querySelector<HTMLElement>("[data-active='true']");
	if (!box || !el) return;
	const top = el.offsetTop;
	const bottom = top + el.offsetHeight;
	if (top < box.scrollTop || bottom > box.scrollTop + box.clientHeight) {
		box.scrollTo({
			top: top - box.clientHeight / 2 + el.offsetHeight / 2,
			behavior: "instant",
		});
	}
});
</script>

{#snippet link(item: PageTree.Item, label: string)}
	{@const active = activeUrl === item.url}
	<li>
		<a
			href={item.url}
			data-active={active}
			aria-current={active ? "page" : undefined}
			class={cn(
				"flex items-center gap-2 rounded-md py-1.5 pr-2.5 pl-2 transition-colors duration-(--motion-fast)",
				mobile && "min-h-11",
				active
					? "bg-surface-card font-medium text-ink"
					: "text-body active:bg-surface-strong hover:bg-surface-card/60 hover:text-ink",
			)}
		>
			<span
				aria-hidden="true"
				class={cn(
					"h-1.5 w-1.5 shrink-0 rounded-full",
					active ? "bg-brand" : "bg-transparent",
				)}
			></span>
			<span class="min-w-0 truncate">{label}</span>
		</a>
	</li>
{/snippet}

<div
	bind:this={scrollEl}
	class={cn(
		"scrollbar-transparent relative",
		!mobile && "sticky top-16 max-h-[calc(100vh-4rem)] overflow-y-auto",
	)}
>
	<nav aria-label="Documentation" class="flex flex-col gap-6 py-6 pr-4 text-sm">
		{#if rootPages.length}
			<ul class="flex flex-col gap-0.5">
				{#each rootPages as item (item.url)}
					{@render link(item, item.name)}
				{/each}
			</ul>
		{/if}

		{#each groups as group (group.name)}
			{@const open = isOpen(group)}
			{@const panelId = `nav-${group.name.toLowerCase().replace(/\W+/g, "-")}`}
			<div class="flex flex-col">
				<!-- One full-width target rather than a dead heading beside a small
				     chevron; the index page moves into the list as "Overview". -->
				<button
					type="button"
					aria-expanded={open}
					aria-controls={panelId}
					onclick={() => (toggled[group.name] = !isOpen(group))}
					class={cn(
						"group flex items-center gap-1.5 rounded-md py-1.5 pr-2 pl-1 text-left text-muted transition-colors duration-(--motion-fast) hover:text-ink",
						mobile && "min-h-11",
					)}
				>
					<ChevronRight
						aria-hidden="true"
						class={cn(
							"h-3.5 w-3.5 shrink-0 transition-transform duration-(--motion-base) ease-out",
							open && "rotate-90",
						)}
					/>
					<!-- `.label-meta` hard-codes its colour, which would beat the hover
					     state; same scale, inheritable colour. -->
					<span
						class="font-mono text-[12px] leading-[1.2] font-medium tracking-[0.025em] uppercase"
					>
						{group.name}
					</span>
					{#if group.prefix}
						<span class="font-mono text-[11px]">{group.prefix}</span>
					{/if}
				</button>

				<div
					class="grid transition-[grid-template-rows] duration-(--motion-base) ease-out"
					style:grid-template-rows={open ? "1fr" : "0fr"}
				>
					<!-- The clipped element carries no padding of its own: under
					     border-box a 0fr track still floors at the padding height. -->
					<div class="overflow-hidden">
						<ul id={panelId} inert={!open} class="flex flex-col gap-0.5 pt-1 pl-3">
							{#if group.overview}
								{@render link(
									group.overview,
									group.overview.name === group.name
										? "Overview"
										: group.overview.name,
								)}
							{/if}
							{#each group.pages as item (item.url)}
								{@render link(item, item.name.slice(group.prefix.length))}
							{/each}
						</ul>
					</div>
				</div>
			</div>
		{/each}
	</nav>
</div>
