import { writeFile } from "node:fs/promises";

const REGISTRY = "https://baby-ui.pages.dev/svelte/r";
// Component CSS only: `tokens` is skipped because it rewrites docvia's theme.
const ITEMS = [
	"roll-text",
	"text-loop",
	"shimmer-text",
	"chart",
	"bar-chart",
	"toggle",
	"select",
	"table-of-contents",
	"theme-toggle",
	"shortcut",
];
const OUT = new URL(
	"../src/lib/styles/baby-ui.components.css",
	import.meta.url,
);

function toCss(rules, indent = "") {
	return Object.entries(rules)
		.map(([key, value]) =>
			typeof value === "object"
				? `${indent}${key} {\n${toCss(value, `${indent}\t`)}${indent}}\n`
				: `${indent}${key}: ${value};\n`,
		)
		.join("");
}

const parts = [];
for (const name of ITEMS) {
	const item = await (await fetch(`${REGISTRY}/${name}.json`)).json();
	if (item.css) parts.push(`/* ${name} */\n${toCss(item.css)}`);
}
await writeFile(
	OUT,
	`/* Generated by scripts/baby-ui-css.mjs. Do not edit. */\n${parts.join("\n")}`,
);
console.log(`wrote ${parts.length} of ${ITEMS.length} items`);
