<script lang="ts">
import type { PageTree } from "@docvia/source";
import { page } from "$app/state";
import { cn } from "$lib/utils";

// The navigation tree is generated by docvia from the compiled `docs`
// collection — see `+layout.server.ts`. The docs site dogfoods the compiler.
let { tree }: { tree: PageTree.Root } = $props();

function titleCase(name: string): string {
	return name
		.split(/[-_/]/)
		.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
		.join(" ");
}

const items = $derived(tree.children.filter((n) => n.type === "page"));
const folders = $derived(tree.children.filter((n) => n.type === "folder"));
</script>

{#snippet link(item: PageTree.Item)}
	{@const active = page.url.pathname === item.url}
	<li>
		<a
			href={item.url}
			class={cn(
				"flex items-center gap-2 rounded-md px-3 py-1.5 transition-colors duration-(--motion-fast)",
				active
					? "bg-surface-card font-medium text-ink"
					: "text-body hover:bg-surface-card/60 hover:text-ink",
			)}
		>
			<span
				class={cn(
					"h-1.5 w-1.5 rounded-full",
					active ? "bg-brand" : "bg-transparent",
				)}
			></span>
			{item.name}
		</a>
	</li>
{/snippet}

<nav class="flex flex-col gap-7 py-6 text-sm">
	{#if items.length}
		<ul class="flex flex-col gap-0.5">
			{#each items as item (item.url)}
				{@render link(item)}
			{/each}
		</ul>
	{/if}

	{#each folders as folder (folder.name)}
		<div class="flex flex-col gap-2">
			<h4
				class="px-3 text-[11px] font-semibold uppercase tracking-widest text-muted"
			>
				{folder.index?.name ?? titleCase(folder.name)}
			</h4>
			<ul class="flex flex-col gap-0.5">
				{#each folder.children as child (child.type === "separator" ? child.name : (child as PageTree.Item).url)}
					{#if child.type === "page"}
						{@render link(child)}
					{:else if child.type === "folder" && child.index}
						{@render link(child.index)}
					{/if}
				{/each}
			</ul>
		</div>
	{/each}
</nav>
