// biome-ignore assist/source/organizeImports: no need
import { parseMarkdown } from "@docvia/core";
import type {
	CompileResult,
	CompilerOptions,
	FileEntry,
	IRDocument,
	PageMeta,
} from "@docvia/ir";
import { transformToIR } from "@docvia/ir";
import { PluginRunner } from "@docvia/plugins";
import {
	extractFrontmatter,
	validateFrontmatter,
	zodSchemaToFrontmatterTs,
} from "@docvia/schema";
import { xxh64 } from "@node-rs/xxhash";
import type { Root as HastRoot } from "hast";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { cpus } from "node:os";
import { extname, join, relative, resolve } from "node:path";
import { performance } from "node:perf_hooks";

// Hashing

export interface HashInputs {
	readonly fileContent: string;
	readonly frontmatter: string;
	readonly configHash: string;
	readonly pluginCacheKeys: string[];
	readonly dependencyHashes: string[];
}

export function computeContentHash(inputs: HashInputs): string {
	const composite = [
		inputs.fileContent,
		inputs.frontmatter,
		inputs.configHash,
		...inputs.pluginCacheKeys,
		...inputs.dependencyHashes,
	].join("\0");
	return xxh64(Buffer.from(composite)).toString(36);
}

// File Reading

async function readFileTree(dir: string): Promise<FileEntry[]> {
	const entries: FileEntry[] = [];

	async function walk(dir: string) {
		const items = await readdir(dir, { withFileTypes: true });
		for (const item of items) {
			const fullPath = join(dir, item.name);
			if (item.isDirectory()) {
				await walk(fullPath);
			} else if (item.isFile() && extname(item.name) === ".md") {
				const content = await readFile(fullPath, "utf-8");
				const hash = xxh64(Buffer.from(content)).toString(36);
				entries.push({
					path: fullPath,
					relativePath: relative(dir, fullPath).replace(/\\/g, "/"),
					content,
					hash,
				});
			}
		}
	}

	await walk(dir);
	return entries;
}

// Parallelism

async function compileParallel<T>(
	items: readonly T[],
	fn: (item: T) => Promise<void>,
	concurrency = Math.max(1, cpus().length - 1),
): Promise<void> {
	let index = 0;
	const workers = Array.from(
		{ length: Math.min(concurrency, items.length) },
		async () => {
			while (true) {
				const i = index++;
				if (i >= items.length) break;
				await fn(items[i] as T);
			}
		},
	);
	await Promise.all(workers);
}


// Route key union for types

function toRouteKeyUnion(routes: Record<string, string>): string[] {
	const routeKeys = Object.keys(routes);
	return routeKeys.length > 0
		? routeKeys.map((route) => `  | "${route}"`)
		: ["  | never"];
}

// ── Module Graph Generation ──────────────────────────────────────────

interface CollectionData {
	name: string;
	baseUrl: string;
	routes: Record<string, string>;
	frontmatterTypeDef: string;
}

function generateDynamicTs(
	collections: readonly CollectionData[],
	syntaxConfig: { theme: string; langs: readonly string[] },
): string {
	const routeMaps = collections
		.map((c) => {
			const entries = Object.entries(c.routes)
				.map(
					([slug, routePath]) =>
						`    ${JSON.stringify(slug)}: ${JSON.stringify(routePath)}`,
				)
				.join(",\n");
			return `  ${JSON.stringify(c.name)}: {\n${entries}\n  }`;
		})
		.join(",\n");

	return `// @ts-nocheck
// Auto-generated by @docvia/compiler — do not edit manually

const routeMap: Record<string, Record<string, string>> = {
${routeMaps}
};

// Global Shiki singleton — shared across dynamic.ts, source/node.ts, and renderer adapters
function _escapeHtml(s) { return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
async function _getHighlighter() {
  const g = globalThis;
  if (g.__docvia_shiki__) return g.__docvia_shiki__;
  if (g.__docvia_shiki_pending__) return g.__docvia_shiki_pending__;
  g.__docvia_shiki_pending__ = (async () => {
    try {
      const _m = 'sh' + 'iki';
      const { createHighlighter } = await import(/* @vite-ignore */ /* webpackIgnore: true */ _m);
      const h = await createHighlighter({
        themes: [${JSON.stringify(syntaxConfig.theme)}],
        langs: ${JSON.stringify(syntaxConfig.langs)},
      });
      g.__docvia_shiki__ = {
        highlight: async (code, lang) => {
          try { return { html: h.codeToHtml(code, { lang, theme: ${JSON.stringify(syntaxConfig.theme)} }) }; }
          catch { return { html: '<pre><code>' + _escapeHtml(code) + '</code></pre>' }; }
        },
      };
    } catch {
      g.__docvia_shiki__ = { highlight: async (code) => ({ html: '<pre><code>' + _escapeHtml(code) + '</code></pre>' }) };
    }
    delete g.__docvia_shiki_pending__;
    return g.__docvia_shiki__;
  })();
  return g.__docvia_shiki_pending__;
}

export async function loadModule(
  collection: string,
  slug: string,
): Promise<{ meta: any; content: any; manifest: any } | undefined> {
  const modulePath = routeMap[collection]?.[slug];
  if (!modulePath) return undefined;
  try {
    // Vite: dynamic import goes through ?docvia transform (SSR + client)
    // Next.js/Turbopack: computed string prevents static analysis, falls to catch
    return await import(/* @vite-ignore */ /* webpackIgnore: true */ modulePath);
  } catch {
    // Node.js / Next.js fallback: compile markdown on-the-fly
    if (typeof window !== 'undefined') return undefined;
    const cleanPath = modulePath.replace(/\\?docvia$/, '');
    const { fileURLToPath } = await import('node:url');
    const resolved = fileURLToPath(new URL(cleanPath, import.meta.url));
    const hl = await _getHighlighter();
    const { loadMarkdown } = await import('@docvia/source/node');
    return loadMarkdown(resolved, { highlighter: hl });
  }
}

export async function getEagerModules(
  collection: string,
): Promise<Record<string, any> | null> {
  if (typeof window === 'undefined') {
    const slugs = Object.keys(routeMap[collection] ?? {});
    const result: Record<string, any> = {};
    for (const slug of slugs) {
      const mod = await loadModule(collection, slug);
      if (mod) result[slug] = mod;
    }
    return Object.keys(result).length > 0 ? result : null;
  }
  return null;
}
`;
}

function generateRegistryTs(
	resolvedOutDir: string,
	components: Record<string, any>,
): string {
	const entries = Object.entries(components);
	const parts: string[] = [
		"// Auto-generated by @docvia/compiler — do not edit manually",
		"import type { ComponentRegistry } from '@docvia/renderer-core';",
	];

	for (const [, entry] of entries) {
		const resolvedComponentPath = resolve(entry.path);
		const relativePath = relative(
			resolvedOutDir,
			resolvedComponentPath,
		).replace(/\\/g, "/");
		const idx = entries.findIndex(([, e]) => e === entry);
		parts.push(
			`import _Component${idx} from ${JSON.stringify(relativePath)};`,
		);
	}

	const mapEntries = entries
		.map(([name, entry], i) => {
			const { hydrate, defaultProps } = entry;
			const props = defaultProps
				? `, defaultProps: ${JSON.stringify(defaultProps)}`
				: "";
			const hydrateStr =
				hydrate !== undefined ? `, hydrate: ${hydrate}` : "";
			return `  ${JSON.stringify(name)}: { component: _Component${i}${hydrateStr}${props} }`;
		})
		.join(",\n");

	parts.push(
		"",
		"export const registry: ComponentRegistry = {",
		"  resolve(name: string) {",
		"    const map: Record<string, NonNullable<ReturnType<ComponentRegistry['resolve']>>> = {",
		mapEntries,
		"    };",
		"    return map[name] ?? null;",
		"  },",
		"};",
	);

	return parts.join("\n");
}

function generateSourceTs(
	collections: readonly CollectionData[],
	config: { components?: Record<string, any> },
): string {
	const parts: string[] = [
		"// Auto-generated by @docvia/compiler — do not edit manually",
		"import { createCollection, createSource } from '@docvia/source/internal';",
		"import { loadModule, getEagerModules } from './dynamic';",
	];

	// Re-export registry if components configured
	const hasRegistry =
		config.components && Object.keys(config.components).length > 0;

	if (hasRegistry) {
		parts.push(
			"export { registry } from './registry';",
		);
	}

	// Per-collection: load eager modules + create collection
	for (const c of collections) {
		const routeKeysLiteral = Object.keys(c.routes)
			.map((k) => JSON.stringify(k))
			.join(", ");

		parts.push(
			"",
			`export const ${c.name} = createCollection<`,
			`  import('./types').${c.name}_Frontmatter,`,
			`  import('./types').${c.name}_RouteKey`,
			`>({`,
			`  name: ${JSON.stringify(c.name)},`,
			`  baseUrl: ${JSON.stringify(c.baseUrl)},`,
			`  routeKeys: [${routeKeysLiteral}] as const,`,
			`  getModule: (slug) => loadModule(${JSON.stringify(c.name)}, slug) as any,`,
			`  getEagerModules: () => getEagerModules(${JSON.stringify(c.name)}),`,
			`  sourceModuleUrl: import.meta.url,`,
			`});`,
		);
	}

	// createSource
	const collectionMap = collections
		.map((c) => `    ${JSON.stringify(c.name)}: ${c.name}`)
		.join(",\n");

	parts.push(
		"",
		"export const docviaSource = createSource({",
		collectionMap,
		"});",
	);

	return parts.join("\n");
}

function generateTypesTs(collections: readonly CollectionData[]): string {
	const parts: string[] = [
		"// Auto-generated by @docvia/compiler — do not edit manually",
	];

	for (const c of collections) {
		const routeKeyUnion = toRouteKeyUnion(c.routes);

		parts.push(
			"",
			`export type ${c.name}_RouteKey =`,
			...routeKeyUnion,
			"  | (string & {});",
			"",
			`export type ${c.name}_Frontmatter = ${c.frontmatterTypeDef};`,
			"",
			`export type ${c.name}_DocPage = import("@docvia/source/runtime").docviaPage<${c.name}_Frontmatter>;`,
		);
	}

	return parts.join("\n");
}

function createdocviaEnvDts(
	collections: readonly CollectionData[],
	relativeOutDir: string,
	hasRegistry: boolean,
): string {
	const exports = collections
		.map((c) => `    export const ${c.name}: typeof source.${c.name};`)
		.join("\n");

	const registryExport = hasRegistry
		? "\n    export const registry: typeof source.registry;"
		: "";

	const registryModule = hasRegistry
		? [
				"",
				"declare module 'docvia/registry' {",
				`    const mod: typeof import('${relativeOutDir}/registry');`,
				"    export const registry: typeof mod.registry;",
				"}",
			].join("\n")
		: "";

	return [
		"declare module 'docvia/source' {",
		`    const source: typeof import('${relativeOutDir}/source');`,
		"    export const docviaSource: typeof source.docviaSource;",
		exports,
		registryExport,
		"}",
		registryModule,
		"",
	].join("\n");
}

// ── Compiler ─────────────────────────────────────────────────────────

export async function compile(
	options: CompilerOptions,
): Promise<CompileResult> {
	const startTime = performance.now();
	const { outDir, config } = options;
	const resolvedOutDir = resolve(outDir);

	const collections = config.collections || [
		{ name: "docs", sourceDir: options.sourceDir, baseUrl: "/" },
	];

	const pluginRunner = new PluginRunner(options.plugins);
	const configHash = xxh64(Buffer.from(JSON.stringify(config))).toString(36);
	const pluginCacheKeys = pluginRunner.getPluginCacheKeys();

	const allPages: PageMeta[] = [];
	const collectionData: CollectionData[] = [];
	let totalFiles = 0;
	let totalCompiled = 0;

	await mkdir(resolvedOutDir, { recursive: true });

	for (const collection of collections) {
		const resolvedSourceDir = resolve(collection.sourceDir);

		// Step 1: Read file tree
		const files = await readFileTree(resolvedSourceDir);
		totalFiles += files.length;

		// Step 2: Compile each file
		const irDocs: IRDocument[] = [];
		const pages: PageMeta[] = [];
		const routes: Record<string, string> = {};

		await compileParallel(files, async (file) => {
			const processedFile = await pluginRunner.runBeforeParse(file);
			const extracted = extractFrontmatter(processedFile.content);
			// biome-ignore lint/suspicious/noExplicitAny: config.schema satisfies ZodObject at runtime
			const frontmatter = validateFrontmatter(
				extracted.data,
				file.path,
				config.frontmatter as any,
			);

			const { ast } = await parseMarkdown(extracted.content, {
				remarkPlugins: config.markdown.remarkPlugins,
			});

			const processedAst = (await pluginRunner.runAfterParse(
				ast,
				processedFile,
			)) as HastRoot;
			const finalAst = (await pluginRunner.runBeforeTransform(
				processedAst,
				frontmatter,
			)) as HastRoot;

			let irDoc = transformToIR(finalAst, frontmatter, file.relativePath);
			const contentHash = computeContentHash({
				fileContent: file.hash,
				frontmatter: JSON.stringify(frontmatter),
				configHash,
				pluginCacheKeys,
				dependencyHashes: [],
			});

			irDoc = { ...irDoc, contentHash };
			irDoc = await pluginRunner.runAfterTransform(irDoc);
			irDoc = await pluginRunner.runBeforeRender(irDoc);

			irDocs.push(irDoc);
			totalCompiled++;

			const slug = irDoc.slug;
			// Path relative to .docvia/ output dir so browser.ts/server.ts imports resolve
			const relPath = relative(resolvedOutDir, resolve(file.path)).replace(/\\/g, "/");
			routes[slug] = `./${relPath}?docvia`;

			pages.push({
				slug,
				title: irDoc.frontmatter.title,
				description: irDoc.frontmatter.description,
				headings: irDoc.headings,
				contentHash,
				lastModified: Date.now(),
				tags: irDoc.frontmatter.tags || [],
				order: irDoc.frontmatter.order,
			});
		});

		// Build frontmatter type definition
		let frontmatterTypeDef: string;
		if (config.frontmatter) {
			// biome-ignore lint/suspicious/noExplicitAny: config.frontmatter satisfies ZodObject at runtime
			frontmatterTypeDef = zodSchemaToFrontmatterTs(
				config.frontmatter as any,
			);
		} else {
			const uniqueFrontmatters = Array.from(
				new Set(irDocs.map((doc) => JSON.stringify(doc.frontmatter))),
			);
			frontmatterTypeDef =
				uniqueFrontmatters.length > 0
					? uniqueFrontmatters.join(" | ")
					: "Record<string, unknown>";
		}

		collectionData.push({
			name: collection.name,
			baseUrl: (
				collection.baseUrl ??
				`/${collection.name === "docs" ? "" : collection.name}`
			).replace(/\/+/g, "/"),
			routes,
			frontmatterTypeDef,
		});

		allPages.push(...pages);
	}

	// Step 3: Write exactly 5 module graph files
	const hasRegistry = !!(
		config.components && Object.keys(config.components).length > 0
	);

	await Promise.all([
		writeFile(join(resolvedOutDir, "dynamic.ts"), generateDynamicTs(collectionData, config.syntax)),
		writeFile(
			join(resolvedOutDir, "source.ts"),
			generateSourceTs(collectionData, config),
		),
		writeFile(
			join(resolvedOutDir, "types.d.ts"),
			generateTypesTs(collectionData),
		),
		// Registry file (client-safe, only if components configured)
		...(hasRegistry
			? [
					writeFile(
						join(resolvedOutDir, "registry.ts"),
						generateRegistryTs(resolvedOutDir, config.components!),
					),
				]
			: []),
	]);

	// Emit docvia-env.d.ts at project root
	const projectRoot = process.cwd();
	const relativeOutDir = relative(projectRoot, resolvedOutDir).replace(
		/\\/g,
		"/",
	);
	const envFilePath = join(projectRoot, "docvia-env.d.ts");
	const envRelativeOutDir = `./${relativeOutDir}`.replace(/\/\/+/g, "/");

	await writeFile(
		envFilePath,
		createdocviaEnvDts(collectionData, envRelativeOutDir, hasRegistry),
	);

	const duration = performance.now() - startTime;

	return {
		pages: allPages,
		searchIndex: "",
		duration,
		stats: {
			total: totalFiles,
			compiled: totalCompiled,
			cached: 0,
		},
	};
}

export { computeContentHash as hashContent };
