// Generated-code emitters. The on-disk `.docvia/` graph serves non-Vite hosts (Next.js, the
// CLI); Vite gets the same modules virtually. Generated code imports only `@docvia/source`.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, join, relative, resolve } from "node:path";
import type { ComponentConfig, docviaConfig } from "@docvia/ir";
import { JSONIFY_TYPE_DECL } from "@docvia/schema";
import { globSync } from "tinyglobby";

export interface CollectionData {
	name: string;
	baseUrl: string;
	routes: Record<string, string>;
	frontmatterTypeDef: string;
}

/** A route's slug and the absolute path of its source markdown file. */
export interface RouteFile {
	readonly slug: string;
	readonly absPath: string;
}

const HEADER = "// Generated by docvia. Do not edit.";
const posix = (p: string): string => p.replace(/\\/g, "/");

// Cheap structural validation: the real list of Shiki language ids changes between releases.
export function warnInvalidShikiLangs(langs: readonly string[]): void {
	const seen = new Set<string>();
	for (const lang of langs) {
		if (typeof lang !== "string" || lang.length === 0) {
			console.warn(
				`[docvia] syntax.langs: ignoring non-string entry: ${JSON.stringify(lang)}`,
			);
			continue;
		}
		if (seen.has(lang)) {
			console.warn(`[docvia] syntax.langs: duplicate language "${lang}"`);
		}
		seen.add(lang);
	}
}

/** Write `content` to `file` unless it already holds exactly that, so watchers stay quiet. */
export async function writeIfChanged(
	file: string,
	content: string,
): Promise<boolean> {
	try {
		if ((await readFile(file, "utf-8")) === content) return false;
	} catch {
		// Missing file: fall through and create it.
	}
	await writeFile(file, content);
	return true;
}

/** `ButtonDemo.svelte` -> `button-demo`. */
export function componentName(file: string): string {
	return basename(file)
		.replace(/.[^.]+$/, "")
		.replace(/([a-z0-9])([A-Z])/g, "$1-$2")
		.replace(/[s_]+/g, "-")
		.toLowerCase();
}

/** Component entries with globs expanded and paths resolved against the project root. */
export function resolveComponents(
	config: docviaConfig,
	projectRoot: string,
): Array<{ name: string; absPath: string; entry: ComponentConfig }> {
	const components = config.components ?? {};
	if (!Array.isArray(components)) {
		return Object.entries(components as Record<string, ComponentConfig>).map(
			([name, entry]) => ({
				name,
				absPath: resolve(projectRoot, entry.path),
				entry,
			}),
		);
	}
	return components.flatMap((item) => {
		if (typeof item !== "string") {
			return [
				{
					name: item.name,
					absPath: resolve(projectRoot, item.path),
					entry: item,
				},
			];
		}
		return globSync(item, { cwd: projectRoot, absolute: true })
			.sort()
			.map((absPath) => ({
				name: componentName(absPath),
				absPath: resolve(absPath),
				entry: { path: absPath },
			}));
	});
}

// --- Registry ---

function registryBody(
	components: ReadonlyArray<{
		name: string;
		specifier: string;
		entry: ComponentConfig;
	}>,
	typed: boolean,
): string {
	const lines = [HEADER];
	if (typed) {
		lines.push("import type { ComponentRegistry } from '@docvia/source';");
	}
	components.forEach((c, i) => {
		lines.push(`import _Component${i} from ${JSON.stringify(c.specifier)};`);
	});
	const entries = components.map((c, i) => {
		const hydrate =
			c.entry.hydrate !== undefined ? `, hydrate: ${c.entry.hydrate}` : "";
		const props = c.entry.defaultProps
			? `, defaultProps: ${JSON.stringify(c.entry.defaultProps)}`
			: "";
		return `  ${JSON.stringify(c.name)}: { component: _Component${i}${hydrate}${props} },`;
	});
	lines.push(
		"",
		`const components${typed ? ": Record<string, NonNullable<ReturnType<ComponentRegistry['resolve']>>>" : ""} = {`,
		...entries,
		"};",
		"",
		`export const registry${typed ? ": ComponentRegistry" : ""} = {`,
		"  resolve: (name) => components[name] ?? null,",
		"};",
		"",
	);
	return lines.join("\n");
}

/** `virtual:docvia/registry`: always present, empty when no components are configured. */
export function generateVirtualRegistry(
	config: docviaConfig,
	projectRoot: string,
): string {
	const components = resolveComponents(config, projectRoot).map((c) => ({
		name: c.name,
		specifier: posix(c.absPath),
		entry: c.entry,
	}));
	return registryBody(components, false);
}

function generateRegistryTs(
	config: docviaConfig,
	projectRoot: string,
	outDir: string,
): string {
	const components = resolveComponents(config, projectRoot).map((c) => {
		const rel = posix(relative(outDir, c.absPath));
		return {
			name: c.name,
			specifier: rel.startsWith(".") ? rel : `./${rel}`,
			entry: c.entry,
		};
	});
	return registryBody(components, true);
}

// --- Source modules ---

/** Code that loads each page's module: static imports (server) or `() => import()` (browser). */
function moduleLoaders(
	collections: readonly CollectionData[],
	specifierOf: (collection: string, slug: string) => string,
	lazy: boolean,
): string[] {
	const imports: string[] = [];
	let idx = 0;
	const body = collections
		.map((c) => {
			const inner = Object.keys(c.routes)
				.map((slug) => {
					const spec = JSON.stringify(specifierOf(c.name, slug));
					if (lazy)
						return `    ${JSON.stringify(slug)}: () => import(${spec}),`;
					const id = `_doc${idx++}`;
					imports.push(`import * as ${id} from ${spec};`);
					return `    ${JSON.stringify(slug)}: ${id},`;
				})
				.join("\n");
			return `  ${JSON.stringify(c.name)}: {\n${inner}\n  },`;
		})
		.join("\n");

	if (lazy) {
		return [
			`const _lazy = {\n${body}\n};`,
			"",
			"function loadModule(collection, slug) {",
			"  const load = _lazy[collection]?.[slug];",
			"  return load ? load() : Promise.resolve(undefined);",
			"}",
			"",
			"async function getEagerModules(collection) {",
			"  const loaders = _lazy[collection];",
			"  if (!loaders) return null;",
			"  const out = {};",
			"  await Promise.all(Object.keys(loaders).map(async (s) => { out[s] = await loaders[s](); }));",
			"  return Object.keys(out).length ? out : null;",
			"}",
		];
	}
	return [
		...imports,
		"",
		`const _modules = {\n${body}\n};`,
		"",
		"function loadModule(collection, slug) {",
		"  return Promise.resolve(_modules[collection]?.[slug]);",
		"}",
		"",
		"function getEagerModules(collection) {",
		"  return _modules[collection] ?? null;",
		"}",
	];
}

function collectionBindings(collections: readonly CollectionData[]): string[] {
	const lines: string[] = [];
	for (const c of collections) {
		const keys = Object.keys(c.routes)
			.map((k) => JSON.stringify(k))
			.join(", ");
		lines.push(
			"",
			`export const ${c.name} = createCollection({`,
			`  name: ${JSON.stringify(c.name)},`,
			`  baseUrl: ${JSON.stringify(c.baseUrl)},`,
			`  routeKeys: [${keys}],`,
			`  getModule: (slug) => loadModule(${JSON.stringify(c.name)}, slug),`,
			`  getEagerModules: () => getEagerModules(${JSON.stringify(c.name)}),`,
			"});",
		);
	}
	const map = collections.map((c) => `  ${c.name},`).join("\n");
	lines.push("", `export const docviaSource = createSource({\n${map}\n});`, "");
	return lines;
}

function sourceModule(
	collections: readonly CollectionData[],
	specifierOf: (collection: string, slug: string) => string,
	lazy: boolean,
): string {
	return [
		"// @ts-nocheck",
		HEADER,
		"import { createCollection, createSource } from '@docvia/source/internal';",
		...moduleLoaders(collections, specifierOf, lazy),
		...collectionBindings(collections),
	].join("\n");
}

/**
 * The `virtual:docvia/source` (eager) or `/browser` (lazy, code-split) module. Markdown is
 * imported by root-relative path, or absolute when it lives outside the root.
 */
export function generateVirtualSource(
	collections: readonly CollectionData[],
	routeFiles: ReadonlyMap<string, readonly RouteFile[]>,
	projectRoot: string,
	lazy = false,
): string {
	const files = new Map<string, string>();
	for (const [name, list] of routeFiles) {
		for (const f of list) {
			const rel = posix(relative(projectRoot, f.absPath));
			const path = rel.startsWith("..") ? posix(f.absPath) : `/${rel}`;
			files.set(`${name}\0${f.slug}`, `${path}?docvia`);
		}
	}
	return sourceModule(
		collections,
		(c, slug) => files.get(`${c}\0${slug}`) ?? "",
		lazy,
	);
}

// --- Types ---

function generateTypesTs(collections: readonly CollectionData[]): string {
	const parts: string[] = [HEADER, "", JSONIFY_TYPE_DECL];
	for (const c of collections) {
		const keys = Object.keys(c.routes);
		parts.push(
			"",
			`export type ${c.name}_RouteKey =`,
			...(keys.length > 0 ? keys.map((k) => `  | "${k}"`) : ["  | never"]),
			"  | (string & {});",
			"",
			`export type ${c.name}_Frontmatter = ${c.frontmatterTypeDef};`,
			"",
			`export type ${c.name}_DocPage = import("@docvia/source").docviaPage<${c.name}_Frontmatter>;`,
		);
	}
	return `${parts.join("\n")}\n`;
}

/**
 * Ambient declarations for every docvia module id. Depends only on `./types` and
 * `@docvia/source`, so `docvia sync` can write it without compiling a bundle.
 */
function generateEnvDts(collections: readonly CollectionData[]): string {
	const collectionDecls = collections.map(
		(c) =>
			`  export const ${c.name}: docviaCollection<import('./types').${c.name}_Frontmatter, import('./types').${c.name}_RouteKey>;`,
	);
	const sourceMap = collections
		.map((c) => `${c.name}: typeof ${c.name}`)
		.join("; ");
	const sourceDecl = (id: string): string =>
		[
			`declare module '${id}' {`,
			"  import type { docviaCollection, docviaSource as Source } from '@docvia/source';",
			...collectionDecls,
			`  export const docviaSource: Source & { collections: { ${sourceMap} } };`,
			"}",
		].join("\n");
	const registryDecl = (id: string): string =>
		[
			`declare module '${id}' {`,
			"  import type { ComponentRegistry } from '@docvia/source';",
			"  export const registry: ComponentRegistry;",
			"}",
		].join("\n");

	// Vite serves `virtual:` ids; Next.js aliases the bare ones.
	return `${[
		HEADER,
		sourceDecl("virtual:docvia/source"),
		sourceDecl("virtual:docvia/source/browser"),
		registryDecl("virtual:docvia/registry"),
		sourceDecl("docvia/source"),
		sourceDecl("docvia/source/browser"),
		registryDecl("docvia/registry"),
	].join("\n\n")}\n`;
}

// --- Disk emit ---

export interface EmitModuleGraphArgs {
	readonly outDir: string;
	readonly projectRoot: string;
	readonly config: docviaConfig;
	readonly collections: readonly CollectionData[];
}

/** Write `types.d.ts` and `env.d.ts` into `outDir`. Enough for `tsc` without a bundler. */
export async function emitTypeDeclarations(
	args: EmitModuleGraphArgs,
): Promise<void> {
	const outDir = resolve(args.outDir);
	await mkdir(outDir, { recursive: true });
	await Promise.all([
		writeIfChanged(
			join(outDir, "types.d.ts"),
			generateTypesTs(args.collections),
		),
		writeIfChanged(join(outDir, "env.d.ts"), generateEnvDts(args.collections)),
	]);
}

/** Write the full module graph (`source.ts`, `browser.ts`, `registry.ts`) plus the type files. */
export async function emitModuleGraphFiles(
	args: EmitModuleGraphArgs,
): Promise<void> {
	const { config, collections, projectRoot } = args;
	const outDir = resolve(args.outDir);
	await mkdir(outDir, { recursive: true });

	const specifierOf = (c: string, slug: string): string =>
		collections.find((x) => x.name === c)?.routes[slug] ?? "";
	await Promise.all([
		writeIfChanged(
			join(outDir, "source.ts"),
			sourceModule(collections, specifierOf, false),
		),
		writeIfChanged(
			join(outDir, "browser.ts"),
			sourceModule(collections, specifierOf, true),
		),
		writeIfChanged(
			join(outDir, "registry.ts"),
			generateRegistryTs(config, projectRoot, outDir),
		),
		emitTypeDeclarations(args),
	]);
}
