// Disk module-graph emitter. Generates the five-file `.docvia/` output
// (dynamic.ts, source.ts, types.d.ts, registry.ts, docvia-env.d.ts) consumed
// by framework bundlers. Pure string generation plus the file writes.

import { mkdir, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import type { docviaConfig } from "@docvia/ir";

export interface CollectionData {
	name: string;
	baseUrl: string;
	routes: Record<string, string>;
	frontmatterTypeDef: string;
}

// ── Shiki language validation ───────────────────────────────────────

// Cheap structural validation — the actual list of valid Shiki language IDs is
// large and changes between Shiki releases. We catch only the obvious mistakes.
export function warnInvalidShikiLangs(langs: readonly string[]): void {
	const seen = new Set<string>();
	for (const lang of langs) {
		if (typeof lang !== "string" || lang.length === 0) {
			console.warn(
				`[docvia] syntax.langs: ignoring non-string entry: ${JSON.stringify(lang)}`,
			);
			continue;
		}
		if (seen.has(lang)) {
			console.warn(`[docvia] syntax.langs: duplicate language "${lang}"`);
		}
		seen.add(lang);
	}
}

// ── Type generation ─────────────────────────────────────────────────

function toRouteKeyUnion(routes: Record<string, string>): string[] {
	const routeKeys = Object.keys(routes);
	return routeKeys.length > 0
		? routeKeys.map((route) => `  | "${route}"`)
		: ["  | never"];
}

// ── Module graph generation ─────────────────────────────────────────

function generateDynamicTs(collections: readonly CollectionData[]): string {
	// Static, in-place imports of every markdown module. The host bundler's
	// `?docvia` loader transforms each one through the configured renderer and
	// bundles the result directly — no IR JSON, no filesystem read, no
	// `import.meta.url` resolution at runtime. Static imports mean SSR/edge
	// bundles include the content, so they work on the edge with no fallback.
	const imports: string[] = [];
	let idx = 0;
	const moduleMaps = collections
		.map((c) => {
			const entries = Object.entries(c.routes)
				.map(([slug, routePath]) => {
					const id = `_doc${idx++}`;
					imports.push(`import * as ${id} from ${JSON.stringify(routePath)};`);
					return `    ${JSON.stringify(slug)}: ${id}`;
				})
				.join(",\n");
			return `  ${JSON.stringify(c.name)}: {\n${entries}\n  }`;
		})
		.join(",\n");

	return `// @ts-nocheck
// Auto-generated by @docvia/compiler — do not edit manually
${imports.join("\n")}

const _modules = {
${moduleMaps}
};

export function loadModule(collection, slug) {
  const m = _modules[collection] && _modules[collection][slug];
  return Promise.resolve(m || undefined);
}

export function getEagerModules(collection) {
  return _modules[collection] || null;
}
`;
}

function generateRegistryTs(
	resolvedOutDir: string,
	components: Record<
		string,
		{ path: string; hydrate?: boolean; defaultProps?: Record<string, unknown> }
	>,
): string {
	const entries = Object.entries(components);
	const parts: string[] = [
		"// Auto-generated by @docvia/compiler — do not edit manually",
		"import type { ComponentRegistry } from '@docvia/renderer-core';",
	];

	entries.forEach(([, entry], idx) => {
		const resolvedComponentPath = resolve(entry.path);
		const relativePath = relative(
			resolvedOutDir,
			resolvedComponentPath,
		).replace(/\\/g, "/");
		parts.push(`import _Component${idx} from ${JSON.stringify(relativePath)};`);
	});

	const mapEntries = entries
		.map(([name, entry], i) => {
			const { hydrate, defaultProps } = entry;
			const props = defaultProps
				? `, defaultProps: ${JSON.stringify(defaultProps)}`
				: "";
			const hydrateStr = hydrate !== undefined ? `, hydrate: ${hydrate}` : "";
			return `    ${JSON.stringify(name)}: { component: _Component${i}${hydrateStr}${props} }`;
		})
		.join(",\n");

	parts.push(
		"",
		"export const registry: ComponentRegistry = {",
		"  resolve(name: string) {",
		"    const map: Record<string, NonNullable<ReturnType<ComponentRegistry['resolve']>>> = {",
		mapEntries,
		"    };",
		"    return map[name] ?? null;",
		"  },",
		"};",
	);

	return parts.join("\n");
}

function generateSourceTs(
	collections: readonly CollectionData[],
	config: { components?: Record<string, unknown> },
): string {
	const parts: string[] = [
		"// Auto-generated by @docvia/compiler — do not edit manually",
		"import { createCollection, createSource } from '@docvia/source/internal';",
		"import { loadModule, getEagerModules } from './dynamic';",
	];

	const hasRegistry =
		config.components && Object.keys(config.components).length > 0;
	if (hasRegistry) {
		parts.push("export { registry } from './registry';");
	}

	for (const c of collections) {
		const routeKeysLiteral = Object.keys(c.routes)
			.map((k) => JSON.stringify(k))
			.join(", ");
		parts.push(
			"",
			`export const ${c.name} = createCollection<`,
			`  import('./types').${c.name}_Frontmatter,`,
			`  import('./types').${c.name}_RouteKey`,
			`>({`,
			`  name: ${JSON.stringify(c.name)},`,
			`  baseUrl: ${JSON.stringify(c.baseUrl)},`,
			`  routeKeys: [${routeKeysLiteral}] as const,`,
			`  getModule: (slug) => loadModule(${JSON.stringify(c.name)}, slug) as any,`,
			`  getEagerModules: () => getEagerModules(${JSON.stringify(c.name)}),`,
			`  sourceModuleUrl: import.meta.url,`,
			`});`,
		);
	}

	const collectionMap = collections
		.map((c) => `    ${JSON.stringify(c.name)}: ${c.name}`)
		.join(",\n");
	parts.push(
		"",
		"export const docviaSource = createSource({",
		collectionMap,
		"});",
	);

	return parts.join("\n");
}

/**
 * Browser entry (`docvia/source/browser`). Same collection API as `source.ts`,
 * but every page is a lazy `() => import("x.md?docvia")` so the bundler
 * code-splits each markdown module — the client only downloads the page it
 * renders. Self-contained (no import of the eager `./dynamic`) so importing it
 * never pulls the whole tree into the client bundle.
 */
function generateBrowserTs(
	collections: readonly CollectionData[],
	config: { components?: Record<string, unknown> },
): string {
	const parts: string[] = [
		// `?docvia` import specifiers have no ambient type, so skip type-checking
		// the file (like dynamic.ts). The typed `createCollection` generics below
		// still flow to consumers via the `docvia/source/browser` declaration.
		"// @ts-nocheck",
		"// Auto-generated by @docvia/compiler — do not edit manually",
		"import { createCollection, createSource } from '@docvia/source/internal';",
	];

	const hasRegistry =
		config.components && Object.keys(config.components).length > 0;
	if (hasRegistry) {
		parts.push("export { registry } from './registry';");
	}

	const lazyBody = collections
		.map((c) => {
			const inner = Object.entries(c.routes)
				.map(
					([slug, path]) =>
						`    ${JSON.stringify(slug)}: () => import(${JSON.stringify(path)})`,
				)
				.join(",\n");
			return `  ${JSON.stringify(c.name)}: {\n${inner}\n  }`;
		})
		.join(",\n");

	parts.push(
		"",
		`const _lazy: Record<string, Record<string, () => Promise<any>>> = {\n${lazyBody}\n};`,
		"",
		"function loadModule(collection: string, slug: string) {",
		"  const l = _lazy[collection]?.[slug];",
		"  return l ? l() : Promise.resolve(undefined);",
		"}",
		"",
		"async function getEagerModules(collection: string) {",
		"  const m = _lazy[collection];",
		"  if (!m) return null;",
		"  const out: Record<string, any> = {};",
		"  await Promise.all(Object.keys(m).map(async (s) => { out[s] = await m[s](); }));",
		"  return Object.keys(out).length ? out : null;",
		"}",
	);

	for (const c of collections) {
		const routeKeysLiteral = Object.keys(c.routes)
			.map((k) => JSON.stringify(k))
			.join(", ");
		parts.push(
			"",
			`export const ${c.name} = createCollection<`,
			`  import('./types').${c.name}_Frontmatter,`,
			`  import('./types').${c.name}_RouteKey`,
			`>({`,
			`  name: ${JSON.stringify(c.name)},`,
			`  baseUrl: ${JSON.stringify(c.baseUrl)},`,
			`  routeKeys: [${routeKeysLiteral}] as const,`,
			`  getModule: (slug) => loadModule(${JSON.stringify(c.name)}, slug) as any,`,
			`  getEagerModules: () => getEagerModules(${JSON.stringify(c.name)}),`,
			`  sourceModuleUrl: import.meta.url,`,
			`});`,
		);
	}

	const collectionMap = collections
		.map((c) => `    ${JSON.stringify(c.name)}: ${c.name}`)
		.join(",\n");
	parts.push(
		"",
		"export const docviaSource = createSource({",
		collectionMap,
		"});",
	);

	return parts.join("\n");
}

function generateTypesTs(collections: readonly CollectionData[]): string {
	const parts: string[] = [
		"// Auto-generated by @docvia/compiler — do not edit manually",
	];
	for (const c of collections) {
		const routeKeyUnion = toRouteKeyUnion(c.routes);
		parts.push(
			"",
			`export type ${c.name}_RouteKey =`,
			...routeKeyUnion,
			"  | (string & {});",
			"",
			`export type ${c.name}_Frontmatter = ${c.frontmatterTypeDef};`,
			"",
			`export type ${c.name}_DocPage = import("@docvia/source/runtime").docviaPage<${c.name}_Frontmatter>;`,
		);
	}
	return parts.join("\n");
}

function createdocviaEnvDts(
	collections: readonly CollectionData[],
	relativeOutDir: string,
	hasRegistry: boolean,
): string {
	const exports = collections
		.map((c) => `    export const ${c.name}: typeof source.${c.name};`)
		.join("\n");
	const browserExports = collections
		.map((c) => `    export const ${c.name}: typeof browser.${c.name};`)
		.join("\n");
	const registryExport = hasRegistry
		? "\n    export const registry: typeof source.registry;"
		: "";
	// The browser module declares `browser`, not `source` — reference the right
	// local so the generated declaration type-checks.
	const registryExportBrowser = hasRegistry
		? "\n    export const registry: typeof browser.registry;"
		: "";

	// Each module is declared under both the Vite virtual id
	// (`virtual:docvia/source`) and the bare specifier the Next.js alias uses
	// (`docvia/source`), so imports type-check in either project.
	const sourceModule = (name: string): string =>
		[
			`declare module '${name}' {`,
			`    const source: typeof import('${relativeOutDir}/source');`,
			"    export const docviaSource: typeof source.docviaSource;",
			exports,
			registryExport,
			"}",
		].join("\n");

	const browserModule = (name: string): string =>
		[
			`declare module '${name}' {`,
			`    const browser: typeof import('${relativeOutDir}/browser');`,
			"    export const docviaSource: typeof browser.docviaSource;",
			browserExports,
			registryExportBrowser,
			"}",
		].join("\n");

	const registryModule = hasRegistry
		? [
				"declare module 'docvia/registry' {",
				`    const mod: typeof import('${relativeOutDir}/registry');`,
				"    export const registry: typeof mod.registry;",
				"}",
			].join("\n")
		: "";

	return [
		sourceModule("virtual:docvia/source"),
		"",
		sourceModule("docvia/source"),
		"",
		browserModule("virtual:docvia/source/browser"),
		"",
		browserModule("docvia/source/browser"),
		"",
		registryModule,
		"",
	].join("\n");
}

// ── Virtual source module (dev) ─────────────────────────────────────

/** A route's slug and the absolute path of its source markdown file. */
export interface RouteFile {
	readonly slug: string;
	readonly absPath: string;
}

/**
 * Generate a single self-contained `docvia/source` module — the dev-server
 * virtual-module equivalent of the on-disk `source.ts` + `dynamic.ts` +
 * `registry.ts` graph. Everything is inlined (no relative inter-file imports);
 * markdown and component paths are absolute so a bundler resolves them
 * wherever the virtual module is placed.
 */
export function generateVirtualSource(
	collections: readonly CollectionData[],
	routeFiles: ReadonlyMap<string, readonly RouteFile[]>,
	config: docviaConfig,
	projectRoot: string,
	/** Emit lazy `() => import()` per page (browser) instead of static imports. */
	lazy = false,
): string {
	const components = config.components ?? {};
	const componentEntries = Object.entries(components);
	const hasRegistry = componentEntries.length > 0;
	const posix = (p: string) => p.replace(/\\/g, "/");

	// Markdown imports use root-relative paths ("/src/docs/x.md") — the form
	// Vite resolves natively. Files outside the project root fall back to an
	// absolute path.
	const toImportPath = (absPath: string): string => {
		const rel = posix(relative(projectRoot, absPath));
		return rel.startsWith("..") ? posix(absPath) : `/${rel}`;
	};

	const parts: string[] = [
		"// Auto-generated docvia virtual source module — do not edit.",
		"import { createCollection, createSource } from '@docvia/source/internal';",
	];

	componentEntries.forEach(([, entry], i) => {
		parts.push(
			`import _Component${i} from ${JSON.stringify(posix(resolve(entry.path)))};`,
		);
	});

	if (lazy) {
		// Browser variant: lazy `() => import()` per page, so the bundler
		// code-splits each markdown module and the client only fetches the page
		// it renders. No content is bundled up front.
		const lazyMapBody = collections
			.map((c) => {
				const files = routeFiles.get(c.name) ?? [];
				const inner = files
					.map(
						(f) =>
							`    ${JSON.stringify(f.slug)}: () => import(${JSON.stringify(`${toImportPath(f.absPath)}?docvia`)})`,
					)
					.join(",\n");
				return `  ${JSON.stringify(c.name)}: {\n${inner}\n  }`;
			})
			.join(",\n");
		parts.push(
			"",
			`const _lazy = {\n${lazyMapBody}\n};`,
			"",
			"function loadModule(collection, slug) {",
			"  const l = _lazy[collection] && _lazy[collection][slug];",
			"  return l ? l() : Promise.resolve(undefined);",
			"}",
			"",
			"async function getEagerModules(collection) {",
			"  const m = _lazy[collection];",
			"  if (!m) return null;",
			"  const out = {};",
			"  await Promise.all(Object.keys(m).map(async (s) => { out[s] = await m[s](); }));",
			"  return Object.keys(out).length ? out : null;",
			"}",
		);
	} else {
		// Server variant: static, in-place imports of every markdown module (no
		// JSON chunks, no runtime dynamic import). The bundler transforms each
		// `?docvia` import through the configured renderer and bundles the
		// result wherever this source module is imported — in SSR/edge that
		// lands them in the server bundle, so there is no filesystem or
		// `import.meta.url` resolution at runtime. Consumers read content
		// through the collection (server-only load paths), so these don't bloat
		// client bundles.
		const moduleImports: string[] = [];
		let importIdx = 0;
		const moduleMapBody = collections
			.map((c) => {
				const files = routeFiles.get(c.name) ?? [];
				const inner = files
					.map((f) => {
						const id = `_doc${importIdx++}`;
						moduleImports.push(
							`import * as ${id} from ${JSON.stringify(`${toImportPath(f.absPath)}?docvia`)};`,
						);
						return `    ${JSON.stringify(f.slug)}: ${id}`;
					})
					.join(",\n");
				return `  ${JSON.stringify(c.name)}: {\n${inner}\n  }`;
			})
			.join(",\n");

		parts.push(...moduleImports);
		parts.push(
			"",
			`const _modules = {\n${moduleMapBody}\n};`,
			"",
			"function loadModule(collection, slug) {",
			"  const m = _modules[collection] && _modules[collection][slug];",
			"  return Promise.resolve(m || undefined);",
			"}",
			"",
			"function getEagerModules(collection) {",
			"  return _modules[collection] || null;",
			"}",
		);
	}

	if (hasRegistry) {
		const mapEntries = componentEntries
			.map(([name, entry], i) => {
				const props = entry.defaultProps
					? `, defaultProps: ${JSON.stringify(entry.defaultProps)}`
					: "";
				const hydrate =
					entry.hydrate !== undefined ? `, hydrate: ${entry.hydrate}` : "";
				return `      ${JSON.stringify(name)}: { component: _Component${i}${hydrate}${props} }`;
			})
			.join(",\n");
		parts.push(
			"",
			"export const registry = {",
			"  resolve(name) {",
			`    const map = {\n${mapEntries}\n    };`,
			"    return map[name] || null;",
			"  },",
			"};",
		);
	}

	for (const c of collections) {
		const routeKeys = (routeFiles.get(c.name) ?? [])
			.map((f) => JSON.stringify(f.slug))
			.join(", ");
		parts.push(
			"",
			`export const ${c.name} = createCollection({`,
			`  name: ${JSON.stringify(c.name)},`,
			`  baseUrl: ${JSON.stringify(c.baseUrl)},`,
			`  routeKeys: [${routeKeys}],`,
			`  getModule: (slug) => loadModule(${JSON.stringify(c.name)}, slug),`,
			`  getEagerModules: () => getEagerModules(${JSON.stringify(c.name)}),`,
			`  sourceModuleUrl: import.meta.url,`,
			`});`,
		);
	}

	const collectionMap = collections
		.map((c) => `  ${JSON.stringify(c.name)}: ${c.name}`)
		.join(",\n");
	parts.push(
		"",
		`export const docviaSource = createSource({\n${collectionMap}\n});`,
	);

	return parts.join("\n");
}

// ── Disk emit ───────────────────────────────────────────────────────

export interface EmitModuleGraphArgs {
	readonly outDir: string;
	readonly projectRoot: string;
	readonly config: docviaConfig;
	readonly collections: readonly CollectionData[];
}

function hasComponentRegistry(config: docviaConfig): boolean {
	return !!(config.components && Object.keys(config.components).length > 0);
}

/**
 * Write only the TypeScript declaration files — `types.d.ts` into `outDir` and
 * the ambient `docvia-env.d.ts` at the project root. These exist purely for
 * IDE type-checking, so the dev plugin emits them even when the runtime module
 * graph is served virtually.
 */
export async function emitTypeDeclarations(
	args: EmitModuleGraphArgs,
): Promise<void> {
	const { outDir, projectRoot, config, collections } = args;
	const resolvedOutDir = resolve(outDir);
	await mkdir(resolvedOutDir, { recursive: true });

	await writeFile(
		join(resolvedOutDir, "types.d.ts"),
		generateTypesTs(collections),
	);

	const relativeOutDir = relative(projectRoot, resolvedOutDir).replace(
		/\\/g,
		"/",
	);
	const envRelativeOutDir = `./${relativeOutDir}`.replace(/\/\/+/g, "/");
	await writeFile(
		join(projectRoot, "docvia-env.d.ts"),
		createdocviaEnvDts(
			collections,
			envRelativeOutDir,
			hasComponentRegistry(config),
		),
	);
}

/**
 * Write the module graph: dynamic.ts / source.ts / browser.ts / types.d.ts /
 * (registry.ts) into `outDir`, plus the ambient `docvia-env.d.ts` at the
 * project root. `source.ts` imports markdown eagerly (server/SSR); `browser.ts`
 * imports it lazily (client code-splitting). Creates `outDir` if absent.
 */
export async function emitModuleGraphFiles(
	args: EmitModuleGraphArgs,
): Promise<void> {
	const { outDir, config, collections } = args;
	const resolvedOutDir = resolve(outDir);

	await mkdir(resolvedOutDir, { recursive: true });

	await Promise.all([
		writeFile(
			join(resolvedOutDir, "dynamic.ts"),
			generateDynamicTs(collections),
		),
		writeFile(
			join(resolvedOutDir, "source.ts"),
			generateSourceTs(collections, config),
		),
		writeFile(
			join(resolvedOutDir, "browser.ts"),
			generateBrowserTs(collections, config),
		),
		...(hasComponentRegistry(config)
			? [
					writeFile(
						join(resolvedOutDir, "registry.ts"),
						generateRegistryTs(
							resolvedOutDir,
							config.components as Record<
								string,
								{
									path: string;
									hydrate?: boolean;
									defaultProps?: Record<string, unknown>;
								}
							>,
						),
					),
				]
			: []),
	]);

	await emitTypeDeclarations(args);
}
