// Generated-code emitters. The on-disk `.docvia/` graph serves non-Vite hosts (Next.js, the
// CLI); Vite gets the same modules virtually. Generated code imports only `@docvia/source`.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, join, relative, resolve } from "node:path";
import type { ComponentConfig, docviaConfig } from "@docvia/ir";
import { JSONIFY_TYPE_DECL } from "@docvia/schema";
import { globSync } from "tinyglobby";

export interface CollectionData {
	name: string;
	baseUrl: string;
	/** Route slugs, for the generated `RouteKey` union. */
	slugs: readonly string[];
	frontmatterTypeDef: string;
}

const HEADER = "// Generated by docvia. Do not edit.";
const posix = (p: string): string => p.replace(/\\/g, "/");

// Cheap structural validation: the real list of Shiki language ids changes between releases.
export function warnInvalidShikiLangs(langs: readonly string[]): void {
	const seen = new Set<string>();
	for (const lang of langs) {
		if (typeof lang !== "string" || lang.length === 0) {
			console.warn(
				`[docvia] syntax.langs: ignoring non-string entry: ${JSON.stringify(lang)}`,
			);
			continue;
		}
		if (seen.has(lang)) {
			console.warn(`[docvia] syntax.langs: duplicate language "${lang}"`);
		}
		seen.add(lang);
	}
}

/** Write `content` to `file` unless it already holds exactly that, so watchers stay quiet. */
export async function writeIfChanged(
	file: string,
	content: string,
): Promise<boolean> {
	try {
		if ((await readFile(file, "utf-8")) === content) return false;
	} catch {
		// Missing file: fall through and create it.
	}
	await writeFile(file, content);
	return true;
}

/** `ButtonDemo.svelte` -> `button-demo`. */
export function componentName(file: string): string {
	return basename(file)
		.replace(/.[^.]+$/, "")
		.replace(/([a-z0-9])([A-Z])/g, "$1-$2")
		.replace(/[s_]+/g, "-")
		.toLowerCase();
}

/** Component entries with globs expanded and paths resolved against the project root. */
export function resolveComponents(
	config: docviaConfig,
	projectRoot: string,
): Array<{ name: string; absPath: string; entry: ComponentConfig }> {
	const components = config.components ?? {};
	if (!Array.isArray(components)) {
		return Object.entries(components as Record<string, ComponentConfig>).map(
			([name, entry]) => ({
				name,
				absPath: resolve(projectRoot, entry.path),
				entry,
			}),
		);
	}
	return components.flatMap((item) => {
		if (typeof item !== "string") {
			return [
				{
					name: item.name,
					absPath: resolve(projectRoot, item.path),
					entry: item,
				},
			];
		}
		return globSync(item, { cwd: projectRoot, absolute: true })
			.sort()
			.map((absPath) => ({
				name: componentName(absPath),
				absPath: resolve(absPath),
				entry: { path: absPath },
			}));
	});
}

// --- Registry ---

function registryBody(
	components: ReadonlyArray<{
		name: string;
		specifier: string;
		entry: ComponentConfig;
	}>,
	typed: boolean,
): string {
	const lines = [HEADER];
	if (typed) {
		lines.push("import type { ComponentRegistry } from '@docvia/source';");
	}
	components.forEach((c, i) => {
		lines.push(`import _Component${i} from ${JSON.stringify(c.specifier)};`);
	});
	const entries = components.map((c, i) => {
		const hydrate =
			c.entry.hydrate !== undefined ? `, hydrate: ${c.entry.hydrate}` : "";
		const props = c.entry.defaultProps
			? `, defaultProps: ${JSON.stringify(c.entry.defaultProps)}`
			: "";
		return `  ${JSON.stringify(c.name)}: { component: _Component${i}${hydrate}${props} },`;
	});
	lines.push(
		"",
		`const components${typed ? ": Record<string, NonNullable<ReturnType<ComponentRegistry['resolve']>>>" : ""} = {`,
		...entries,
		"};",
		"",
		`export const registry${typed ? ": ComponentRegistry" : ""} = {`,
		"  resolve: (name) => components[name] ?? null,",
		"};",
		"",
	);
	return lines.join("\n");
}

/** `virtual:docvia/registry`: always present, empty when no components are configured. */
export function generateVirtualRegistry(
	config: docviaConfig,
	projectRoot: string,
): string {
	const components = resolveComponents(config, projectRoot).map((c) => ({
		name: c.name,
		specifier: posix(c.absPath),
		entry: c.entry,
	}));
	return registryBody(components, false);
}

function generateRegistryTs(
	config: docviaConfig,
	projectRoot: string,
	outDir: string,
): string {
	const components = resolveComponents(config, projectRoot).map((c) => {
		const rel = posix(relative(outDir, c.absPath));
		return {
			name: c.name,
			specifier: rel.startsWith(".") ? rel : `./${rel}`,
			entry: c.entry,
		};
	});
	return registryBody(components, true);
}

// --- Source modules ---

/** The shared tail: one `createCollection` per collection plus the aggregate `docviaSource`. */
function collectionExports(
	collections: readonly { name: string; baseUrl: string }[],
	metaOf: (name: string) => string,
	bodiesOf: (name: string) => string,
): string[] {
	const lines = [
		"// @ts-nocheck",
		HEADER,
		"import { createCollection, createSource } from '@docvia/source/internal';",
	];
	for (const c of collections) {
		lines.push(
			"",
			`export const ${c.name} = createCollection({`,
			`  name: ${JSON.stringify(c.name)},`,
			`  baseUrl: ${JSON.stringify(c.baseUrl)},`,
			`  meta: ${metaOf(c.name)},`,
			`  bodies: ${bodiesOf(c.name)},`,
			"});",
		);
	}
	const map = collections.map((c) => `  ${c.name},`).join("\n");
	lines.push("", `export const docviaSource = createSource({\n${map}\n});`, "");
	return lines;
}

/**
 * The Vite source module. Bodies are lazy `import.meta.glob` entries, so nothing compiles up
 * front. Frontmatter comes inline from `index` when given, else from `only=meta` modules.
 */
export function generateVirtualSource(
	collections: readonly { name: string; baseUrl: string; dir: string }[],
	projectRoot: string,
	index?: ReadonlyMap<string, IndexedPage>,
): string {
	// Same key Vite's glob uses for a file in a virtual module.
	const key = (abs: string) =>
		`/${posix(relative(projectRoot, abs))}`.replace(/^\/\//, "/");
	// Virtual modules only accept root-relative globs; "/../x" still reaches outside the root.
	const glob = (dir: string) =>
		JSON.stringify(
			`/${posix(relative(projectRoot, dir))}/**/*.md`.replace(/^\/\//, "/"),
		);
	const dirOf = (name: string) =>
		collections.find((c) => c.name === name)?.dir ?? projectRoot;
	const inlineMeta = (name: string) => {
		const entries = [...(index?.values() ?? [])]
			.filter((p) => p.collection === name)
			.map(
				(p) =>
					`    ${JSON.stringify(key(p.absPath))}: ${JSON.stringify(p.meta)},`,
			);
		return `{\n${entries.join("\n")}\n  }`;
	};
	return collectionExports(
		collections,
		(name) =>
			index
				? inlineMeta(name)
				: `import.meta.glob(${glob(dirOf(name))}, { eager: true, import: "meta", query: "?docvia&collection=${name}&only=meta" })`,
		(name) =>
			`import.meta.glob(${glob(dirOf(name))}, { query: "?docvia&collection=${name}" })`,
	).join("\n");
}

export interface IndexedPage {
	readonly collection: string;
	readonly absPath: string;
	readonly meta: Record<string, unknown>;
}

/** The on-disk source module for hosts without `import.meta.glob` (Next.js, the CLI). */
function generateDiskSource(
	collections: readonly { name: string; baseUrl: string }[],
	pages: readonly IndexedPage[],
	outDir: string,
): string {
	const spec = (absPath: string) => {
		const rel = posix(relative(outDir, absPath));
		return `${rel.startsWith(".") ? rel : `./${rel}`}?docvia`;
	};
	const object = (entries: string[]) => `{\n${entries.join("\n")}\n  }`;
	const of = (name: string) => pages.filter((p) => p.collection === name);
	return collectionExports(
		collections,
		(name) =>
			object(
				of(name).map(
					(p) => `    ${JSON.stringify(p.absPath)}: ${JSON.stringify(p.meta)},`,
				),
			),
		(name) =>
			object(
				of(name).map(
					(p) =>
						`    ${JSON.stringify(p.absPath)}: () => import(${JSON.stringify(spec(p.absPath))}),`,
				),
			),
	).join("\n");
}

// --- Types ---

function generateTypesTs(collections: readonly CollectionData[]): string {
	const parts: string[] = [HEADER, "", JSONIFY_TYPE_DECL];
	for (const c of collections) {
		const keys = c.slugs;
		parts.push(
			"",
			`export type ${c.name}_RouteKey =`,
			...(keys.length > 0 ? keys.map((k) => `  | "${k}"`) : ["  | never"]),
			"  | (string & {});",
			"",
			`export type ${c.name}_Frontmatter = ${c.frontmatterTypeDef};`,
			"",
			`export type ${c.name}_DocPage = import("@docvia/source").docviaPage<${c.name}_Frontmatter>;`,
		);
	}
	return `${parts.join("\n")}\n`;
}

/**
 * Ambient declarations for every docvia module id. Depends only on `./types` and
 * `@docvia/source`, so `docvia sync` can write it without compiling a bundle.
 */
function generateEnvDts(collections: readonly CollectionData[]): string {
	const collectionDecls = collections.map(
		(c) =>
			`  export const ${c.name}: docviaCollection<import('./types').${c.name}_Frontmatter, import('./types').${c.name}_RouteKey>;`,
	);
	const sourceMap = collections
		.map((c) => `${c.name}: typeof ${c.name}`)
		.join("; ");
	const sourceDecl = (id: string): string =>
		[
			`declare module '${id}' {`,
			"  import type { docviaCollection, docviaSource as Source } from '@docvia/source';",
			...collectionDecls,
			`  export const docviaSource: Source & { collections: { ${sourceMap} } };`,
			"}",
		].join("\n");
	const registryDecl = (id: string): string =>
		[
			`declare module '${id}' {`,
			"  import type { ComponentRegistry } from '@docvia/source';",
			"  export const registry: ComponentRegistry;",
			"}",
		].join("\n");

	// Vite serves `virtual:` ids; Next.js aliases the bare ones.
	return `${[
		HEADER,
		sourceDecl("virtual:docvia/source"),
		sourceDecl("virtual:docvia/source/browser"),
		registryDecl("virtual:docvia/registry"),
		sourceDecl("docvia/source"),
		sourceDecl("docvia/source/browser"),
		registryDecl("docvia/registry"),
	].join("\n\n")}\n`;
}

// --- Disk emit ---

export interface EmitModuleGraphArgs {
	readonly outDir: string;
	readonly projectRoot: string;
	readonly config: docviaConfig;
	readonly collections: readonly CollectionData[];
	/** Frontmatter per page, for the disk source module. */
	readonly pages?: readonly IndexedPage[];
}

/** Write `types.d.ts` and `env.d.ts` into `outDir`. Enough for `tsc` without a bundler. */
export async function emitTypeDeclarations(
	args: EmitModuleGraphArgs,
): Promise<void> {
	const outDir = resolve(args.outDir);
	await mkdir(outDir, { recursive: true });
	await Promise.all([
		writeIfChanged(
			join(outDir, "types.d.ts"),
			generateTypesTs(args.collections),
		),
		writeIfChanged(join(outDir, "env.d.ts"), generateEnvDts(args.collections)),
	]);
}

/** Write `source.ts`, `browser.ts`, `registry.ts` and the type files, for non-Vite hosts. */
export async function emitModuleGraphFiles(
	args: EmitModuleGraphArgs,
): Promise<void> {
	const { config, collections, projectRoot } = args;
	const outDir = resolve(args.outDir);
	await mkdir(outDir, { recursive: true });

	// Bodies are lazy in both, so the browser module is the same file.
	const source = generateDiskSource(collections, args.pages ?? [], outDir);
	await Promise.all([
		writeIfChanged(join(outDir, "source.ts"), source),
		writeIfChanged(join(outDir, "browser.ts"), source),
		writeIfChanged(
			join(outDir, "registry.ts"),
			generateRegistryTs(config, projectRoot, outDir),
		),
		emitTypeDeclarations(args),
	]);
}
