<script lang="ts">
import data from "#lib/benchmarks/comparison.json";
import { Bar, BarChart, BarTooltip, BarXAxis, BarYAxis } from "#lib/components/charts/bar-chart/index.ts";
import { ChartContainer } from "#lib/components/charts/chart/index.ts";
import BentoCard from "#lib/components/site/bento-card.svelte";
import Section from "#lib/components/site/section.svelte";

// Generated by .local/bench/compare-json.mjs from results.md; never edit numbers by hand.
type Row = { pages: number; tool: string } & Record<string, number | string | null>;
const vite = data.vite as Row[];
const next = data.next as Row[];
const sizes = [...new Set(vite.map((r) => r.pages))];
const big = Math.max(...sizes);

const series = {
	fumadocs: { label: "fumadocs", color: "var(--muted-soft)" },
	react: { label: "docvia + React", color: "var(--brand)" },
	svelte: { label: "docvia + Svelte", color: "var(--brand-strong)" },
};
const pick = (rows: Row[], tool: string, pages: number, key: string) =>
	Number(rows.find((r) => r.tool === tool && r.pages === pages)?.[key] ?? 0);
const grouped = (key: string, scale = 1) =>
	sizes.map((pages) => ({
		name: `${pages.toLocaleString("en")} pages`,
		fumadocs: +(pick(vite, "fumadocs async", pages, key) / scale).toFixed(1),
		react: +(pick(vite, "docvia react", pages, key) / scale).toFixed(1),
		svelte: +(pick(vite, "docvia svelte", pages, key) / scale).toFixed(1),
	}));

const builds = grouped("build", 1000);
const edits = grouped("edit");
const nextBuilds = [...new Set(next.map((r) => r.pages))].map((pages) => ({
	name: `${pages.toLocaleString("en")} pages`,
	fumadocs: +(pick(next, "fumadocs", pages, "build") / 1000).toFixed(1),
	react: +(pick(next, "docvia", pages, "build") / 1000).toFixed(1),
}));

// Every metric at the largest size, lower is better; docvia's losses stay in.
const metrics = [
	{ key: "ready", label: "Dev server ready", unit: "ms" },
	{ key: "firstPage", label: "Cold start to first page", unit: "ms" },
	{ key: "edit", label: "Edit to visible", unit: "ms" },
	{ key: "build", label: "Production SSR build", unit: "ms" },
	{ key: "ssrImport", label: "Server bundle cold import", unit: "ms" },
	{ key: "heapMB", label: "Heap after import", unit: "MB" },
	{ key: "renderWarm", label: "Render every page, warm", unit: "ms" },
	{ key: "htmlKB", label: "HTML for every page", unit: "KB" },
];
const tools = ["fumadocs async", "docvia react", "docvia svelte"];
const fmt = (v: number, unit: string) => (unit === "ms" && v >= 1000 ? `${(v / 1000).toFixed(1)} s` : `${v.toLocaleString("en")} ${unit}`);
const table = metrics.map((m) => {
	const values = tools.map((t) => pick(vite, t, big, m.key));
	return { ...m, values, best: Math.min(...values) };
});
const m = data.machine;
</script>

<Section id="numbers" number={3} title="numbers." description="docvia and fumadocs on the same Markdown pages, same machine, best of 2 runs. Lower is better.">
	<ul class="mb-4 flex flex-wrap gap-x-5 gap-y-2 font-mono text-xs text-muted">
		{#each Object.values(series) as s}
			<li class="flex items-center gap-2"><span class="size-2.5 rounded-sm" style="background: {s.color}"></span>{s.label}</li>
		{/each}
	</ul>
	<div class="grid gap-3 lg:grid-cols-3">
		<BentoCard title="Production build, Vite SSR" description="Seconds to build every page.">
			<ChartContainer config={series} title="Production build time" aspect="square">
				<BarChart data={builds} xKey="name" xLabel="Pages">
					<BarYAxis tickFormatter={(v) => `${v} s`} />
					<BarXAxis />
					<Bar dataKey="fumadocs" />
					<Bar dataKey="react" />
					<Bar dataKey="svelte" />
					<BarTooltip />
				</BarChart>
			</ChartContainer>
		</BentoCard>

		<BentoCard title="Edit to visible, dev" description="Milliseconds from saving a page to seeing it.">
			<ChartContainer config={series} title="Edit to visible" aspect="square">
				<BarChart data={edits} xKey="name" xLabel="Pages">
					<BarYAxis tickFormatter={(v) => `${v} ms`} />
					<BarXAxis />
					<Bar dataKey="fumadocs" />
					<Bar dataKey="react" />
					<Bar dataKey="svelte" />
					<BarTooltip />
				</BarChart>
			</ChartContainer>
		</BentoCard>

		<BentoCard title="Production build, Next.js" description="next build with Turbopack, seconds.">
			<ChartContainer config={series} title="Next.js build time" aspect="square">
				<BarChart data={nextBuilds} xKey="name" xLabel="Pages">
					<BarYAxis tickFormatter={(v) => `${v} s`} />
					<BarXAxis />
					<Bar dataKey="fumadocs" />
					<Bar dataKey="react" />
					<BarTooltip />
				</BarChart>
			</ChartContainer>
		</BentoCard>
	</div>

	<BentoCard class="mt-3" title="All measurements at {big.toLocaleString('en')} pages" description="Vite {data.versions.vite} SSR. The best value in each row is highlighted.">
		<div class="-mx-1 overflow-x-auto">
			<table class="w-full min-w-[34rem] text-sm">
				<thead>
					<tr class="border-b border-dashed border-hairline-strong text-left font-mono text-xs text-muted">
						<th class="py-2 pr-4 font-normal">Metric</th>
						<th class="py-2 pr-4 font-normal">fumadocs</th>
						<th class="py-2 pr-4 font-normal">docvia + React</th>
						<th class="py-2 font-normal">docvia + Svelte</th>
					</tr>
				</thead>
				<tbody>
					{#each table as row}
						<tr class="border-b border-dashed border-hairline-strong last:border-0">
							<td class="py-2 pr-4 text-body">{row.label}</td>
							{#each row.values as v}
								<td class="py-2 pr-4 font-mono tabular-nums {v === row.best ? 'text-brand-ink' : 'text-muted'}">{fmt(v, row.unit)}</td>
							{/each}
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</BentoCard>
	<p class="mt-4 font-mono text-xs text-muted">
		fumadocs-mdx {data.versions["fumadocs-mdx"]} + fumadocs-core {data.versions["fumadocs-core"]}, Next {data.versions.next}.
		{m.cpu}, {m.ramGB} GB, Node {m.node.replace(/^v/, "")}, {data.date}. Synthetic pages with headings, lists, tables and code.
	</p>
</Section>
